# Generated by Django 5.1.5 on 2025-01-31 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lib_ancestral_domain',
            fields=[
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('last_modified_by', models.UUIDField(editable=False, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=5000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('ancestral_domain_description', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='lib_city',
            fields=[
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('last_modified_by', models.UUIDField(editable=False, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=5000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('city_code', models.CharField(db_index=True, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=250)),
                ('city_nick', models.CharField(max_length=120)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='lib_civil_status',
            fields=[
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('last_modified_by', models.UUIDField(editable=False, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=5000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('civil_status_description', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='lib_educational_attainment',
            fields=[
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('last_modified_by', models.UUIDField(editable=False, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=5000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('educational_attainment_description', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='lib_fund_source',
            fields=[
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('last_modified_by', models.UUIDField(editable=False, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=5000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('fund_source_description', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='lib_lgu_level',
            fields=[
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('last_modified_by', models.UUIDField(editable=False, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=5000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('lgu_level_description', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='lib_lgu_position',
            fields=[
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('last_modified_by', models.UUIDField(editable=False, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=5000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('lgu_position_description', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='lib_mode',
            fields=[
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('last_modified_by', models.UUIDField(editable=False, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=5000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('mode_description', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='lib_occupation',
            fields=[
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('last_modified_by', models.UUIDField(editable=False, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=5000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('occupation_description', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='lib_province',
            fields=[
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('last_modified_by', models.UUIDField(editable=False, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=5000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('province_code', models.CharField(db_index=True, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('province_name', models.CharField(max_length=250)),
                ('province_nick', models.CharField(max_length=120)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='lib_region',
            fields=[
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('last_modified_by', models.UUIDField(editable=False, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=5000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('region_code', models.CharField(db_index=True, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=250)),
                ('region_nick', models.CharField(max_length=120)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='lib_sex',
            fields=[
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('last_modified_by', models.UUIDField(editable=False, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=5000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('sex_description', models.CharField(max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='module',
            fields=[
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('last_modified_by', models.UUIDField(editable=False, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=5000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_description', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='permission',
            fields=[
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('last_modified_by', models.UUIDField(editable=False, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=5000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_description', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('last_modified_by', models.UUIDField(editable=False, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=5000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_description', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('last_modified_by', models.UUIDField(editable=False, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=5000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ext_name', models.CharField(blank=True, max_length=10)),
                ('password', models.CharField(blank=True, max_length=500)),
                ('region_code', models.CharField(default='', max_length=12)),
                ('prov_code', models.CharField(default='', max_length=12)),
                ('city_code', models.CharField(default='', max_length=12)),
                ('brgy_code', models.CharField(default='', max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='lib_ancestral_domain_coverage',
            fields=[
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('last_modified_by', models.UUIDField(editable=False, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=5000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('region_code', models.CharField(max_length=12)),
                ('prov_code', models.CharField(max_length=12)),
                ('city_code', models.CharField(max_length=12)),
                ('brgy_code', models.CharField(max_length=12)),
                ('ancestral_domain_coverage_description', models.CharField(max_length=250)),
                ('ancestral_domain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lib_ancestral_domain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='lib_brgy',
            fields=[
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('last_modified_by', models.UUIDField(editable=False, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=5000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('brgy_code', models.CharField(db_index=True, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('brgy_name', models.CharField(max_length=250)),
                ('brgy_nick', models.CharField(max_length=120)),
                ('sort_order', models.IntegerField(default=0)),
                ('city_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lib_city')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='lib_cycle',
            fields=[
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('last_modified_by', models.UUIDField(editable=False, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=5000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('cycle_description', models.CharField(max_length=128)),
                ('fund_source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lib_fund_source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lib_city',
            name='province_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lib_province'),
        ),
        migrations.AddField(
            model_name='lib_province',
            name='region_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lib_region'),
        ),
        migrations.CreateModel(
            name='user_access',
            fields=[
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('last_modified_by', models.UUIDField(editable=False, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=5000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.module')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
