version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-service
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000" # Adjust the port to match your backend service
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-service
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000" # Default port for Next.js
    env_file:
      - ./frontend/.env

  database:
    image: postgres:15
    container_name: database-service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dswd@123
      POSTGRES_DB: kcisdb

volumes:
  postgres_data:
