  export interface IAllocation{
    id: string,
    date_allocation: string | null,
    region_code: string,
    pap_id: number,
    budget_year_id: number,
    appropriation_source_id: number,
    appropriation_type_id: number,
    record_status_id: number,
    created_date: string,
    created_by: string,
    last_modified_date: string | null,
    last_modified_by: string | null,
    push_status_id: number,
    push_date: string | null,
    deleted_date: string | null,
    deleted_by: string | null,
    is_deleted: boolean,
    remarks: string | null,
    user_id: string | null,
  }

  export interface IAllocationUacs{
    id: string,
    allocation_id: string,
    allotment_class_id: number,
    component_id: number,
    expense_id: number,
    allocation_amount: number,
    created_date: string,
    created_by: string,
    last_modified_date: string | null,
    last_modified_by: string | null,
    push_status_id: number,
    push_date: string | null,
    deleted_date: string | null,
    deleted_by: string | null,
    is_deleted: boolean,
    remarks: string | null,
    user_id: string | null,
  }